/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        hearth: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
          950: '#052e16',
        },
        sage: {
          50: '#f6f7f6',
          100: '#e3e8e3',
          200: '#c7d2c7',
          300: '#a3b5a3',
          400: '#7d947d',
          500: '#637a63',
          600: '#4e614e',
          700: '#3e4d3e',
          800: '#344034',
          900: '#2c352c',
        },
        brand: {
          peach: '#E89271',
          tan: '#F0D4BE',
          dark: '#16191E',
          blue: '#3875E8',
          slate: '#5A7285',
        },
        // Hearth Care Sanctuary tokens
        "secondary-fixed-dim": "#b3ccbf",
        "secondary-mint": "#8fa89b",
        "tertiary-champagne": "#d4a373",
        "on-surface": "#211a17",
        "on-error-container": "#93000a",
        "on-primary-container": "#fffbff",
        "error": "#ba1a1a",
        "secondary-fixed": "#cee9da",
        "tertiary-fixed": "#ffdcbd",
        "outline-variant": "#d8c1c0",
        "inverse-on-surface": "#fdeee8",
        "tertiary-fixed-dim": "#f0bd8b",
        "surface-container-highest": "#eedfda",
        "surface-container-low": "#fff1ec",
        "primary": "#8c4846",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#3b080b",
        "on-tertiary-fixed-variant": "#623f18",
        "surface-dim": "#e6d7d2",
        "inverse-primary": "#ffb3b0",
        "surface-container": "#faebe6",
        "tertiary": "#7b542b",
        "secondary-container": "#cee9da",
        "tertiary-container": "#966c41",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#092017",
        "surface-tint": "#8f4a49",
        "on-surface-variant": "#534342",
        "background": "#fff8f6",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#733333",
        "on-secondary-container": "#52695e",
        "primary-container": "#aa5f5e",
        "on-background": "#211a17",
        "surface-container-high": "#f4e5e0",
        "primary-fixed": "#ffdad8",
        "inverse-surface": "#372f2b",
        "surface": "#fff8f6",
        "surface-variant": "#eedfda",
        "primary-fixed-dim": "#ffb3b0",
        "outline": "#867371",
        "on-tertiary-container": "#fffbff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#2c1600",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#354c41",
        "surface-bright": "#fff8f6",
        "secondary": "#4c6358",
        "teal-btn": "#6da2b8",
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'sans-serif'],
        handwritten: ['"Caveat"', 'cursive'],
        serif: ['Newsreader', 'Literata', 'serif'],
        newsreader: ['Newsreader', 'serif'],
        headline: ['Newsreader', 'Literata', 'serif'],
        'headline-sm': ['Newsreader', 'Literata', 'serif'],
        'headline-md': ['Newsreader', 'Literata', 'serif'],
        'headline-lg': ['Newsreader', 'Literata', 'serif'],
        'display': ['Newsreader', 'Literata', 'serif'],
        'display-lg': ['Newsreader', 'serif'],
        'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'title-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'title-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'title-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'margin': '1rem',
        'margin-tablet': '2rem',
        'margin-desktop': '3rem',
        'gutter': '1.25rem',
        'gutter-desktop': '2rem',
      }
    },
  },
  plugins: [],
}
